#!/usr/bin/env python3
"""Local-program pilot on a previously frozen memory; only reader calls allowed.

The supplied memory root must be a trusted local checkpoint generated by this
repository. Its checksum and literal passages are verified before reuse. The
reader may use a different model; extraction provenance is recorded explicitly.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import pickle
import statistics
import sys
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def load_memory(memory_root, corpus, embedding_key):
    for path in sorted(Path(memory_root).rglob("memory.json")):
        saved = json.loads(path.read_text(encoding="utf-8"))
        identity = saved.get("identity", {})
        ids = identity.get("corpus", {}).get("question_ids", [])
        if not ids or ids[0].split(":qa")[0] != corpus.questions[0].qid.split(":qa")[0]:
            continue
        if identity.get("embedder") != embedding_key:
            continue
        raw = path.with_name("memory.pkl").read_bytes()
        if hashlib.sha256(raw).hexdigest() != saved["sha256"]:
            raise ValueError("Frozen memory checksum mismatch")
        kg, extraction = pickle.loads(raw)  # trusted, repository-generated checkpoint only
        literal = lambda c: [(p.pid, p.title, p.text) for p in c.passages]
        if literal(kg.corpus) != literal(corpus):
            continue
        if any(f.pid not in corpus.pids for f in kg.facts):
            raise ValueError("Frozen facts reference a passage outside the corpus")
        kg.corpus = corpus
        return kg, extraction, {"path": str(path.resolve()), "sha256": saved["sha256"],
                                "extraction_model": identity.get("model"),
                                "ie": identity.get("ie"),
                                "literal_passages_verified": True,
                                "provenance_metadata_may_differ": True}
    raise FileNotFoundError("No frozen memory with identical ordered passage ids/title/text and embedding model")


def pick_questions(questions, limit):
    if not limit or limit >= len(questions):
        return questions
    # Fixed round robin for a cheap smoke covering the question types. Only the
    # evaluation harness reads labels; the retriever receives no gold metadata.
    groups = {kind: [q for q in questions if q.qtype == kind]
              for kind in ("single-hop", "multi-hop", "temporal", "open-domain")}
    chosen = []
    while len(chosen) < limit:
        progressed = False
        for group in groups.values():
            if group and len(chosen) < limit:
                chosen.append(group.pop(0)); progressed = True
        if not progressed:
            break
    return chosen


def check_manifest(path, identity, resume=False):
    # Dataclass tuples become JSON arrays; normalize before comparison.
    identity = json.loads(json.dumps(identity, ensure_ascii=False))
    if path.exists():
        if not resume or json.loads(path.read_text(encoding="utf-8")) != identity:
            raise ValueError("Existing run differs or --resume was omitted; choose another output")
    else:
        path.write_text(json.dumps(identity, indent=2, ensure_ascii=False), encoding="utf-8")


def report(rows, output, retrieval_only):
    mean = lambda key: statistics.mean(float(r.get(key, 0)) for r in rows) if rows else 0
    planning = sum(sum(v.get("tokens_prompt", 0)+v.get("tokens_resposta", 0)
                       for stage, v in r.get("uso_llm", {}).get("por_estagio", {}).items()
                       if stage != "qa") for r in rows)
    tokens = sum(r.get("uso_llm", {}).get("total", {}).get("tokens_prompt", 0) +
                 r.get("uso_llm", {}).get("total", {}).get("tokens_resposta", 0) for r in rows)
    value = {"n": len(rows), "retrieval_only": retrieval_only,
             "planning_and_summary_tokens": planning, "reader_tokens_per_question": tokens/max(1,len(rows)),
             "f1": None if retrieval_only else mean("f1_locomo"), "bleu1": None if retrieval_only else mean("bleu1_locomo"),
             "mean_retrieval_seconds": mean("latencia_recuperacao_s"),
             "categories": {kind: {"n": len(group),
                                    "f1": None if retrieval_only else statistics.mean(r.get("f1_locomo",0) for r in group),
                                    "bleu1": None if retrieval_only else statistics.mean(r.get("bleu1_locomo",0) for r in group)}
                            for kind in sorted({r["tipo"] for r in rows})
                            if (group := [r for r in rows if r["tipo"] == kind])}}
    (output / "summary.json").write_text(json.dumps(value, indent=2, ensure_ascii=False), encoding="utf-8")
    lines = ["# Piloto: múltiplos planos locais", "",
             f"{len(rows)} perguntas. Apenas recuperação: {retrieval_only}.", "",
             "Memória existente reutilizada; custo de construção não incluído. "
             "O reranker é um modelo de relevância, não um parser semântico treinado para planos.", "",
             f"Tokens de planejamento/resumo: **{planning}**. Tokens do reader por pergunta: **{value['reader_tokens_per_question']:.0f}**.", "",
             "| Categoria | n | F1 | BLEU-1 |", "|---|---:|---:|---:|"]
    if not retrieval_only:
        for kind, group in value["categories"].items():
            lines.append(f"| {kind} | {group['n']} | {100*group['f1']:.2f} | {100*group['bleu1']:.2f} |")
        lines += [f"| total | {len(rows)} | {100*value['f1']:.2f} | {100*value['bleu1']:.2f} |", "",
                  "Uma conversa é um piloto de desenvolvimento; não demonstra ganho frente ao cascade. "
                  "Confira o modelo do reader e o modelo da extração no manifesto antes de comparar runs."]
    (output / "report.md").write_text("\n".join(lines)+"\n", encoding="utf-8")
    return value


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--data-root", type=Path, required=True, help="prepared run containing conversations/convNN/data")
    p.add_argument("--memory-root", type=Path, required=True, help="trusted local frozen memory checkpoints")
    p.add_argument("--conversation", type=int, default=0, help="zero-based: 0 is the first conversation")
    p.add_argument("--questions", type=int, default=0, help="0=all; otherwise deterministic balanced smoke")
    p.add_argument("--question-types", nargs="+", choices=["single-hop","multi-hop","temporal","open-domain"],
                   help="evaluation-only selection; never passed to the planner")
    p.add_argument("--output", type=Path, default=ROOT / "runs/local-plans-conv00")
    p.add_argument("--backend", choices=["openai", "stub"], default="stub")
    p.add_argument("--model", default="gpt-4o-mini")
    p.add_argument("--base-url", default=None)
    p.add_argument("--embed-model", default="BAAI/bge-m3")
    p.add_argument("--reranker", default=None)
    p.add_argument("--device", default="cpu")
    p.add_argument("--threads", type=int, default=4)
    p.add_argument("--beam", type=int, default=None)
    p.add_argument("--depth", type=int, default=3)
    p.add_argument("--candidates", type=int, default=None)
    p.add_argument("--keep", type=int, default=3)
    p.add_argument("--plan-version", choices=["v1", "v2", "lite"], default="v2")
    p.add_argument("--executions", type=int, default=None)
    p.add_argument("--starts", type=int, default=None)
    p.add_argument("--retrieval-only", action="store_true")
    p.add_argument("--resume", action="store_true")
    args = p.parse_args()
    lite = args.plan_version == 'lite'
    args.beam = args.beam if args.beam is not None else (8 if lite else 32)
    args.candidates = args.candidates if args.candidates is not None else (24 if lite else 96)
    args.executions = args.executions if args.executions is not None else (256 if lite else 4000)
    args.starts = args.starts if args.starts is not None else (6 if lite else 12)
    args.reranker = args.reranker if args.reranker is not None else ('' if lite else 'BAAI/bge-reranker-v2-m3')
    if lite and args.reranker:
        p.error('Lite requires no reranker')
    if not 0 <= args.conversation <= 9 or args.questions < 0:
        p.error("conversation must be 0..9 and questions nonnegative")
    if args.backend == "stub" and not args.retrieval_only:
        p.error("Use --backend openai for real answers, or --retrieval-only for offline validation")
    os.environ["WRAG_EMBED_DEVICE"] = args.device
    if args.base_url is not None:
        os.environ["OPENAI_BASE_URL"] = args.base_url
    for key in ("WRAG_REFLECTION_STUDY_ROOT", "WRAG_CONTROLLED_ROOT", "WRAG_FROZEN_MEMORY_ROOT"):
        os.environ.pop(key, None)
    if not lite:
        import torch
        torch.set_num_threads(args.threads)
    from wrag import config as C
    from wrag.data import load_dataset
    from wrag.eval.runner import _answer_standard
    from wrag.llm import get_llm
    from wrag.methods.base import IndexContext
    from wrag.methods.witnessrag import WitnessRAGRetriever
    from wrag.util import sha
    data = args.data_root / "conversations" / f"conv{args.conversation:02d}" / "data"
    if not data.exists():
        data = args.data_root / "data"
    corpus = load_dataset("locomo", data_dir=data)
    if lite:
        from wrag.witness.local_lite import FrozenOnlyEmbedder
        key = 'st-' + args.embed_model.replace('/', '_')
        if C.EMBED_MAX_SEQ_LENGTH:
            key += f'-len{C.EMBED_MAX_SEQ_LENGTH}'
        embedder = FrozenOnlyEmbedder(key)
    else:
        from wrag.embed import SentenceTransformerEmbedder
        embedder = SentenceTransformerEmbedder(args.embed_model, device=args.device)
    kg, extraction, provenance = load_memory(args.memory_root, corpus, embedder.cache_key())
    cfg = C.RunConfig(dataset=corpus.name, top_k=5, methods=("witnessrag",))
    cfg.witness = C.WitnessConfig(local_plans=True, proof_controller=True, proof_verify=False,
        hybrid_fallback=True, fact_delivery="facts", fact_fill="question", fact_time="both",
        fact_rerank=args.reranker, local_plan_beam=args.beam, local_plan_depth=args.depth,
        local_plan_candidates=args.candidates, local_plan_keep=args.keep,
        local_plan_version=args.plan_version, local_plan_executions=args.executions,
        local_plan_starts=args.starts,
        proof_importance_normal=0, proof_importance_strong=0)
    cfg.qa = C.QAConfig(evidence_reader=True, reader_reflection=True, temporal_annotations=True,
                        max_tokens=128, answer_guard=False)
    eligible=[q for q in corpus.questions if not args.question_types or q.qtype in args.question_types]
    questions = pick_questions(eligible, args.questions)
    cfg.n_questions = len(questions)
    reader = get_llm(args.backend, deployment=args.model) if args.backend != "stub" else get_llm("stub")
    original_chat = reader.chat
    def reader_only_chat(*values, **kwargs):
        if args.retrieval_only or kwargs.get("stage") != "qa":
            raise AssertionError(f"Disallowed generative stage: {kwargs.get('stage')}")
        return original_chat(*values, **kwargs)
    reader.chat = reader_only_chat
    ctx = IndexContext(corpus, reader, embedder, cfg, extraction=extraction, kg=kg)
    r = WitnessRAGRetriever(ctx); r.index()
    identity = {"protocol": "local-multiplan-"+args.plan_version, "reader": args.model,
                "backend": args.backend, "endpoint": args.base_url,
                "memory": provenance, "configuration": cfg.to_dict(),
                "questions": [q.qid for q in questions], "retrieval_only": args.retrieval_only,
                "code": sha([(str(f.relative_to(ROOT)), hashlib.sha256(f.read_bytes()).hexdigest())
                             for f in sorted((ROOT / "wrag").rglob("*.py"))])}
    args.output.mkdir(parents=True, exist_ok=True)
    manifest = args.output / "manifest.json"
    check_manifest(manifest, identity, args.resume)
    path = args.output / "predictions.jsonl"
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()] if path.exists() else []
    done = {row["qid"] for row in rows}
    for q in questions:
        if q.qid in done:
            continue
        if args.retrieval_only:
            retrieval = r.retrieve(q)
            row = {"qid": q.qid, "tipo": q.qtype, "diagnosticos": retrieval.diagnostics,
                   "latencia_recuperacao_s": retrieval.latency_s, "uso_llm": reader.usage.snapshot()}
        else:
            row = _answer_standard("witnessrag-local", r, corpus, q, cfg)
        with path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(row, ensure_ascii=False, default=str)+"\n")
        rows.append(row)
        report(rows, args.output, args.retrieval_only)
        d = row["diagnosticos"]["local_plans"]
        print(f"{len(rows)}/{len(questions)} {q.qtype} plans={d['generated']} "
              f"selected={len(d['selected'])} latency={row['latencia_recuperacao_s']:.1f}s", flush=True)
    result = report(rows, args.output, args.retrieval_only)
    print(json.dumps(result, ensure_ascii=False), flush=True)


if __name__ == "__main__":
    main()
